/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBemorlarRouteImport } from './routes/dashboard.bemorlar'
import { Route as DashboardPalatalarRouteImport } from './routes/dashboard.palatalar'
import { Route as DashboardShifokorlarRouteImport } from './routes/dashboard.shifokorlar'
import { Route as DashboardTolovlarRouteImport } from './routes/dashboard.tolovlar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBemorlarRoute = DashboardBemorlarRouteImport.update({
  id: '/bemorlar',
  path: '/bemorlar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPalatalarRoute = DashboardPalatalarRouteImport.update({
  id: '/palatalar',
  path: '/palatalar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShifokorlarRoute = DashboardShifokorlarRouteImport.update({
  id: '/shifokorlar',
  path: '/shifokorlar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTolovlarRoute = DashboardTolovlarRouteImport.update({
  id: '/tolovlar',
  path: '/tolovlar',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/bemorlar': typeof DashboardBemorlarRoute
  '/dashboard/palatalar': typeof DashboardPalatalarRoute
  '/dashboard/shifokorlar': typeof DashboardShifokorlarRoute
  '/dashboard/tolovlar': typeof DashboardTolovlarRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/bemorlar': typeof DashboardBemorlarRoute
  '/dashboard/palatalar': typeof DashboardPalatalarRoute
  '/dashboard/shifokorlar': typeof DashboardShifokorlarRoute
  '/dashboard/tolovlar': typeof DashboardTolovlarRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/bemorlar': typeof DashboardBemorlarRoute
  '/dashboard/palatalar': typeof DashboardPalatalarRoute
  '/dashboard/shifokorlar': typeof DashboardShifokorlarRoute
  '/dashboard/tolovlar': typeof DashboardTolovlarRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/bemorlar'
    | '/dashboard/palatalar'
    | '/dashboard/shifokorlar'
    | '/dashboard/tolovlar'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/bemorlar'
    | '/dashboard/palatalar'
    | '/dashboard/shifokorlar'
    | '/dashboard/tolovlar'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/bemorlar'
    | '/dashboard/palatalar'
    | '/dashboard/shifokorlar'
    | '/dashboard/tolovlar'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bemorlar': {
      id: '/dashboard/bemorlar'
      path: '/bemorlar'
      fullPath: '/dashboard/bemorlar'
      preLoaderRoute: typeof DashboardBemorlarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/palatalar': {
      id: '/dashboard/palatalar'
      path: '/palatalar'
      fullPath: '/dashboard/palatalar'
      preLoaderRoute: typeof DashboardPalatalarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shifokorlar': {
      id: '/dashboard/shifokorlar'
      path: '/shifokorlar'
      fullPath: '/dashboard/shifokorlar'
      preLoaderRoute: typeof DashboardShifokorlarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tolovlar': {
      id: '/dashboard/tolovlar'
      path: '/tolovlar'
      fullPath: '/dashboard/tolovlar'
      preLoaderRoute: typeof DashboardTolovlarRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBemorlarRoute: typeof DashboardBemorlarRoute
  DashboardPalatalarRoute: typeof DashboardPalatalarRoute
  DashboardShifokorlarRoute: typeof DashboardShifokorlarRoute
  DashboardTolovlarRoute: typeof DashboardTolovlarRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBemorlarRoute: DashboardBemorlarRoute,
  DashboardPalatalarRoute: DashboardPalatalarRoute,
  DashboardShifokorlarRoute: DashboardShifokorlarRoute,
  DashboardTolovlarRoute: DashboardTolovlarRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
